import { createHash } from 'node:crypto';
import type { Plugin } from 'vite';

// Zero-dependency PWA service worker generator.
//
// At build time we enumerate every emitted chunk/asset and bake a precache list
// + a content-derived VERSION into `sw.js`. Because the VERSION only changes
// when the built output changes, a fresh deploy produces a byte-different
// service worker → the browser installs it as a "waiting" worker and the app
// shows an update toast (prompt model — we never skipWaiting on our own).
//
// The SW precaches the app shell for full offline play and runtime-caches any
// other same-origin GET it sees.

// Public assets copied verbatim from `public/` (not part of the JS bundle).
// Precached best-effort so a missing one never fails install.
const OPTIONAL_PUBLIC = [
  'manifest.webmanifest',
  'favicon.svg',
  'icons.svg',
  'pwa-192.png',
  'pwa-512.png',
  'pwa-maskable-512.png',
  'apple-touch-icon.png',
];

const swTemplate = (version: string, shell: string, precache: string[], optional: string[]) => `// AUTO-GENERATED by vite-plugin-sw. Do not edit.
const VERSION = ${JSON.stringify(version)};
const CACHE = 'ww-cache-' + VERSION;
const SHELL = ${JSON.stringify(shell)};
const PRECACHE = ${JSON.stringify(precache)};
const OPTIONAL = ${JSON.stringify(optional)};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await cache.addAll(PRECACHE);
    await Promise.allSettled(OPTIONAL.map((u) => cache.add(u)));
    // Intentionally NOT calling skipWaiting(): the page prompts the user first.
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys.filter((k) => k.startsWith('ww-cache-') && k !== CACHE).map((k) => caches.delete(k))
    );
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // SPA navigations → serve the precached app shell (instant + offline).
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE);
      const shell = await cache.match(SHELL);
      if (shell) return shell;
      try { return await fetch(req); } catch { return Response.error(); }
    })());
    return;
  }

  // Everything else same-origin → cache-first, runtime-cache on miss.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = await cache.match(req);
    if (hit) return hit;
    try {
      const net = await fetch(req);
      if (net && net.ok && net.type === 'basic') cache.put(req, net.clone());
      return net;
    } catch {
      return hit || Response.error();
    }
  })());
});
`;

export function serviceWorkerPlugin(): Plugin {
  let base = '/';
  return {
    name: 'vite-plugin-sw',
    apply: 'build',
    configResolved(config) {
      base = config.base || '/';
    },
    generateBundle(_options, bundle) {
      const files = Object.keys(bundle).sort();
      const shell = base + 'index.html';
      // Precache the app shell (index.html may not be in the bundle map at this
      // hook's timing, so add it explicitly) + every emitted JS/CSS/asset.
      const precache = Array.from(new Set([shell, ...files.map((f) => base + f)]));
      const optional = OPTIONAL_PUBLIC.map((f) => base + f);
      const version = createHash('sha256').update([shell, ...files].join('\n')).digest('hex').slice(0, 12);
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: swTemplate(version, shell, precache, optional),
      });
    },
  };
}
